package com.snap.newsapp

import android.content.Context
import android.content.Intent
import android.net.Uri
import android.util.Log
import androidx.browser.customtabs.CustomTabColorSchemeParams
import androidx.browser.customtabs.CustomTabsIntent

/**
 * WebLauncher implementation for Android that opens URLs using Chrome Custom Tabs.
 * 
 * This provides an in-app browser experience on Android with a seamless transition.
 * Falls back to opening in the default browser if Chrome Custom Tabs are unavailable.
 *
 * Note: The WebLauncher interface is generated by Valdi from the @ExportProxy annotation
 * It will be available after running: valdi projectsync
 */
class WebLauncherImpl(private val context: Context) : WebLauncher {
    
    companion object {
        private const val TAG = "WebLauncher"
        private const val TOOLBAR_COLOR = 0xFF007AFF.toInt() // Blue color matching iOS
    }
    
    /**
     * Opens a URL in Chrome Custom Tabs or the default browser.
     *
     * @param url The URL string to open
     */
    override fun openUrl(url: String) {
        if (url.isBlank()) {
            Log.e(TAG, "Cannot open empty URL")
            return
        }
        
        try {
            val uri = Uri.parse(url)
            
            if (uri == null || uri.scheme == null) {
                Log.e(TAG, "Invalid URL format: $url")
                return
            }
            
            // Try to open with Chrome Custom Tabs
            openWithCustomTabs(uri)
            
        } catch (e: Exception) {
            Log.e(TAG, "Failed to open URL: $url", e)
            
            // Fallback: Try to open in external browser
            try {
                openInExternalBrowser(url)
            } catch (fallbackException: Exception) {
                Log.e(TAG, "Fallback also failed for URL: $url", fallbackException)
            }
        }
    }
    
    /**
     * Opens the URL using Chrome Custom Tabs with custom styling.
     */
    private fun openWithCustomTabs(uri: Uri) {
        try {
            // Configure custom tab colors to match app theme
            val colorSchemeParams = CustomTabColorSchemeParams.Builder()
                .setToolbarColor(TOOLBAR_COLOR)
                .setNavigationBarColor(TOOLBAR_COLOR)
                .build()
            
            // Build the Custom Tabs intent with animations and styling
            val customTabsIntent = CustomTabsIntent.Builder()
                .setDefaultColorSchemeParams(colorSchemeParams)
                .setShowTitle(true)
                .setUrlBarHidingEnabled(true)
                .setStartAnimations(context, android.R.anim.slide_in_left, android.R.anim.slide_out_right)
                .setExitAnimations(context, android.R.anim.slide_in_left, android.R.anim.slide_out_right)
                .build()
            
            // Launch the Custom Tab
            customTabsIntent.launchUrl(context, uri)
            Log.d(TAG, "Opened URL in Custom Tab: $uri")
            
        } catch (e: Exception) {
            Log.w(TAG, "Custom Tabs not available, falling back to external browser", e)
            openInExternalBrowser(uri.toString())
        }
    }
    
    /**
     * Opens the URL in the device's default browser as a fallback.
     */
    private fun openInExternalBrowser(url: String) {
        val intent = Intent(Intent.ACTION_VIEW, Uri.parse(url))
        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        context.startActivity(intent)
        Log.d(TAG, "Opened URL in external browser: $url")
    }
}
