//
//  SCWebLauncherImpl.m
//  NewsApp
//
//  WebLauncher implementation for iOS that opens URLs in SFSafariViewController
//

#import "SCWebLauncherImpl.h"
#import <SafariServices/SafariServices.h>

// Note: SCWebLauncher protocol is generated by Valdi from the @ExportProxy annotation
// It will be available after running: valdi projectsync
// Expected location: Generated headers from your build output

@interface SCWebLauncherImpl ()
@end

@implementation SCWebLauncherImpl

#pragma mark - Initialization

- (instancetype)initWithViewController:(UIViewController *)viewController {
    self = [super init];
    if (self) {
        _presentingViewController = viewController;
    }
    return self;
}

- (instancetype)init {
    // Get the root view controller as fallback
    UIViewController *rootViewController = [UIApplication sharedApplication].keyWindow.rootViewController;
    return [self initWithViewController:rootViewController];
}

#pragma mark - SCWebLauncher Protocol

- (void)openUrlWithUrl:(NSString *)url {
    if (!url || url.length == 0) {
        NSLog(@"[WebLauncher] Error: Cannot open empty URL");
        return;
    }
    
    NSURL *nsUrl = [NSURL URLWithString:url];
    if (!nsUrl) {
        NSLog(@"[WebLauncher] Error: Invalid URL format: %@", url);
        return;
    }
    
    // Ensure we have a presenting view controller
    UIViewController *presenter = self.presentingViewController;
    if (!presenter) {
        presenter = [self findTopViewController];
    }
    
    if (!presenter) {
        NSLog(@"[WebLauncher] Error: No view controller available to present Safari");
        // Fallback: Open in external Safari
        [self openInExternalBrowser:nsUrl];
        return;
    }
    
    // Open URL in SFSafariViewController on the main thread
    dispatch_async(dispatch_get_main_queue(), ^{
        [self presentSafariViewControllerWithURL:nsUrl fromViewController:presenter];
    });
}

#pragma mark - Private Methods

/**
 * Presents an SFSafariViewController with the given URL
 */
- (void)presentSafariViewControllerWithURL:(NSURL *)url fromViewController:(UIViewController *)presenter {
    SFSafariViewController *safariViewController = [[SFSafariViewController alloc] initWithURL:url];
    
    // Customize appearance to match app theme
    if (@available(iOS 10.0, *)) {
        safariViewController.preferredBarTintColor = [UIColor colorWithRed:0.0 green:0.48 blue:1.0 alpha:1.0]; // #007AFF
        safariViewController.preferredControlTintColor = [UIColor whiteColor];
    }
    
    if (@available(iOS 11.0, *)) {
        safariViewController.dismissButtonStyle = SFSafariViewControllerDismissButtonStyleClose;
    }
    
    // Present the Safari view controller
    [presenter presentViewController:safariViewController animated:YES completion:^{
        NSLog(@"[WebLauncher] Opened URL in Safari: %@", url.absoluteString);
    }];
}

/**
 * Opens the URL in the external Safari browser as a fallback
 */
- (void)openInExternalBrowser:(NSURL *)url {
    if (@available(iOS 10.0, *)) {
        [[UIApplication sharedApplication] openURL:url options:@{} completionHandler:^(BOOL success) {
            if (success) {
                NSLog(@"[WebLauncher] Opened URL in external Safari: %@", url.absoluteString);
            } else {
                NSLog(@"[WebLauncher] Failed to open URL: %@", url.absoluteString);
            }
        }];
    } else {
        // Fallback for iOS 9 and earlier
        [[UIApplication sharedApplication] openURL:url];
    }
}

/**
 * Finds the topmost view controller in the hierarchy
 */
- (UIViewController *)findTopViewController {
    UIViewController *topController = [UIApplication sharedApplication].keyWindow.rootViewController;
    
    while (topController.presentedViewController) {
        topController = topController.presentedViewController;
    }
    
    if ([topController isKindOfClass:[UINavigationController class]]) {
        UINavigationController *navController = (UINavigationController *)topController;
        topController = navController.topViewController;
    }
    
    if ([topController isKindOfClass:[UITabBarController class]]) {
        UITabBarController *tabController = (UITabBarController *)topController;
        topController = tabController.selectedViewController;
    }
    
    return topController;
}

@end
